### PR TITLE
Appschema smart

### PR DESCRIPTION
**Pull request by jemacchi**
SmartAppSchema module development. 
DomainModelBuilder and DomainModel entities implementation. 
JDBCDatastoreMetadata implementation.
Includes Online tests. 
GML and AppSchema visitors.

### CODE REVIEW

**Comment by nmco** [comment]
@jemacchi this PR includes 16000+ commits, I'm pretty sure something is wrong here.

**Comment by jemacchi** [comment]
Yes, I noticed that. That was reason I asked in tech chat channel to reconfirm some steps, since I'm doing samething I did for geowebcache or others. Anyway we can check together, but basically: created my branch from my geoserver fork, then pushed to my branch and finally created a PR from  jemacchi/geoserver:appschema-smart (my fork:branch) to merge it in  geosolutions-it/geoserver:appschema-smart  (my branch starts from jemacchi/geoserver:master) 
Here my git remote -v:
```
geosolutions	https://github.com/geosolutions-it/geoserver (fetch)
geosolutions	https://github.com/geosolutions-it/geoserver (push)
origin	https://github.com/jemacchi/geoserver.git (fetch)
origin	https://github.com/jemacchi/geoserver.git (push)
upstream	https://github.com/geoserver/geoserver (fetch)
upstream	https://github.com/geoserver/geoserver (push)
```

**Comment by nmco** [comment]
@jemacchi this PR is not clean I guess you need to align GeoSolutions master wiht GeoServer master, can you do it?

**Comment by nmco** [comment]
@jemacchi this is still not a clean PR, as we discussed by chat please align GeoSolutions with GeoServer master.

**Comment by nmco** [comment]
HELLO??????

**Comment by jemacchi** [comment]
@nmco I'm taking a look now to align GeoSolutions master wiht GeoServer master.

**Comment by jemacchi** [comment]
> HELLO??????

@nmco please check if the PR is clean now. It's only 1 commit with full list of files from AppSchema Smart)

**Pull request closed without merging**
