### PR TITLE
[GEOS-11322] MapML WMS Vector Representation include query filter

### PR DESCRIPTION
**Pull request by turingtestfail**
wildcard import removed

abstract parent needs the mime

file license

cleanup

fixed test issues with projection

validating sld filters

added getStyleQuery test

Moved to util class

cleanup

test fix

removed unnecessary inheritance

cleanup

pr response

PR responses and fix to resource vs layer metadata issue

  

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by prushforth** [comment]
I think it looks good.  I was able to mix tile, image and features in a single request, and unsetting the global WMS checkbox reverted to a single image query.  Nicely done, and thank you!  I will document it tomorrow or Friday.

**Comment by prushforth** [comment]
If I merge this PR with the commits in [this PR](https://github.com/geosolutions-it/geoserver/pull/363), will I be able to evaluate SLD application to MapML vector requests?  Or maybe this PR already has code that allows features to be requested (but not clipped)?  Thanks

**Comment by prushforth** [comment]
Anyway, looks good to me!

**Review by prushforth — COMMENTED** [review]
I forgot to add a note to the docs regarding single/multiple extent processing with mixed content types for each layer.  Is it too late to do that?

Edit: I just pushed a commit with that documentation update.

**Comment by aaime** [comment]
Merged on main repository

**Pull request closed without merging**
