### PR TITLE
Removing sharding support

### PR DESCRIPTION
**Pull request by dromagnoli**
https://osgeo-org.atlassian.net/browse/GEOS-11471

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
Before starting to check changes and code, I run a simple grep finding more leftovers:

```
aaime@colossus ~/devel/git-gs (mapml-sharding) $ git grep -i shard
... // some unrelated lines containing shard removed here
src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLConstants.java:    /** SHARD_SERVER_PATTERN */
src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLConstants.java:    public static final String SHARD_SERVER_PATTERN = "shardServerPattern";
src/extension/mapml/src/main/java/org/geoserver/mapml/xml/Input.java: *       &lt;attribute name="shard" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
src/extension/mapml/src/main/java/org/geoserver/mapml/xml/Input.java:    @XmlAttribute(name = "shard")
src/extension/mapml/src/main/java/org/geoserver/mapml/xml/Input.java:    protected String shard;
src/extension/mapml/src/main/java/org/geoserver/mapml/xml/Input.java:     * Gets the value of the shard property.
src/extension/mapml/src/main/java/org/geoserver/mapml/xml/Input.java:    public String getShard() {
src/extension/mapml/src/main/java/org/geoserver/mapml/xml/Input.java:        return shard;
src/extension/mapml/src/main/java/org/geoserver/mapml/xml/Input.java:     * Sets the value of the shard property.
src/extension/mapml/src/main/java/org/geoserver/mapml/xml/Input.java:    public void setShard(String value) {
src/extension/mapml/src/main/java/org/geoserver/mapml/xml/Input.java:        this.shard = value;
src/extension/mapml/src/main/resources/schema/mapml.rnc:  attribute shard { text }?,
src/extension/mapml/src/main/resources/schema/mapml.xsd:      <xs:attribute name="shard"/>
src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java:    public void testLegacyShardingConfig() throws Exception {
src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java:        // Although sharding support has been removed, test that everything is working fine
src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java:        // and no configured sharding is being used even if it was configured (simulating
src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java:        // an old layer configured in the past with sharding enabled)
src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java:        mm.put("mapml.enableSharding", true);
src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java:        mm.put("mapml.shardList", "server1,server2,server3");
src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java:        mm.put("mapml.shardServerPattern", "{s}.example.com");
src/extension/mapml/src/test/java/org/geoserver/mapml/MapMLWMSTest.java:                "count(//html:map-input[@list='servers'][@type='hidden'][@shard='true'][@name='s'])",
```

**Comment by dromagnoli** [comment]
> git grep -i shard

Fixed most of them (I was missing a commit when switching to the customDimesion thing).
Note that the testLegacyShardingConfig is actually using sharding config params to mimic a legacy layer that has been configured with sharding, making sure that things are still working and running but no sharding is being used.

I also did a test by configuring a layer with sharding on a default Geoserver, then used the version where sharding code was removed and GeoServer and that layer was still working fine after the restart with the new code.

**Review by aaime — APPROVED** [review]
LGTM

**Comment by aaime** [comment]
@prushforth what do you think? Good for public publishing?

**Review by prushforth — APPROVED** [review]

**Comment by dromagnoli** [comment]
FYI: the official PR against GeoServer main is here:
https://github.com/geoserver/geoserver/pull/7789

**Comment by aaime** [comment]
Closing as we have an official PR.

**Pull request closed without merging**
