### PR TITLE
Geos 11353 map ml default image format

### PR DESCRIPTION
**Pull request by turingtestfail**
# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by prushforth** [comment]
Looks like it saves the image setting so that it gets used in for example the WMS request dropdown, but the saved value isn't reflected in the UI when you go back into edit the layer to change it - it displays image/png always as far as I can tell.

I'll keep playing with it, let you know if I spot anything else.  Thanks!

**Comment by turingtestfail** [comment]
> Looks like it saves the image setting so that it gets used in for example the WMS request dropdown, but the saved value isn't reflected in the UI when you go back into edit the layer to change it - it displays image/png always as far as I can tell.
> 
> I'll keep playing with it, let you know if I spot anything else. Thanks!

Thanks - looks like default call was overwritting model value.  It is removed and is working now.

**Comment by prushforth** [comment]
> Thanks - looks like default call was overwritting model value. It is removed and is working now.

Yep, that is saving and working fine.

I noticed that the preview text/html; subtype=mapml is not using the saved mime type:
image
...
image
...
image
...
image
...
image



, but the raw WMS request from the dropdown list of formats will generate a mapml document that does use the saved mime type, (but it's not in the parameters of the generated link):

image

...

but is in the templated link in the mapml document:
image

I would have thought that the selected default should get put into the preview via parameters?

**Comment by turingtestfail** [comment]
> > Thanks - looks like default call was overwritting model value. It is removed and is working now.
> 
> Yep, that is saving and working fine.
> 
> I noticed that the preview text/html; subtype=mapml is not using the saved mime type: image ... image ... image ... image ... , but the raw WMS request from the dropdown list of formats will generate a mapml document that does use the saved mime type:
> 
> image
> 
> (but it's not in the parameters of the generated link):
> 
> image
> 
> ...
> 
> but is in the templated link in the mapml document: image
> 
> I would have thought that the selected default should get put into the preview via parameters?

@prushforth Just made a push that makes sure that the HTML preview gets passed the layer setting.

**Comment by prushforth** [comment]
> @prushforth Just made a push that makes sure that the HTML preview gets passed the layer setting.

Working very well now, thanks!  I like the way it prevents changes to the default image media type while the layer is set to "Use Features".  Also confirm that it works for Layer Groups.  

Looks Good To Me! tm

**Comment by prushforth** [comment]
@turingtestfail has this one been merged upstream?  I just noticed that you requested my review some time ago, but I thought it had been merged a while back?

**Review by prushforth — APPROVED** [review]

**Comment by aaime** [comment]
It has indeed been merged upstream: https://github.com/geoserver/geoserver/pull/7612
Closing here.

**Pull request closed without merging**
