### PR TITLE
[GEOS-11486] Mapml Adding customdims to mapMl document

### PR DESCRIPTION
**Pull request by dromagnoli**
https://osgeo-org.atlassian.net/browse/GEOS-11486

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
@prushforth what do you think of this one?

**Comment by prushforth** [comment]
While I do see the custom dimension in the capabilities document, and of course the GetMap response in the preview reflects the default value, I don't see it reflected in any of the URLs in the text/mapml document as a DIM_WHATEVER variable / parameter, and I was hoping it would get reflected into a \<map-select name="DIM_WHATEVER"> so that it could be queried by the client and be useful as a way to query the content.  My understanding of how to use WMS dimensions is a bit limited, but if you create a custom dimension for a layer that has say 50 values for that dimension, you could present them for selection by the client.  That's what I've done so far with non-custom dimensions, at least.

**Comment by dromagnoli** [comment]
Hi @prushforth.
I think what are you looking for is already in place but I'm not sure if I understood correctly so I'm reporting how it works with the updated code on a sample layer rtadcp_customdim where I have configured a dim_corr custom dimension based on a corr4 existing attribute of the underlying featureType:

This is how the mapml HTML client looks like:
image

Where we can select one of the possible values and see the output reflected in the preview:
Selecting dim_corr = 23:
image

Selecting dim_corr = 24:
image

And when requesting the MapML output, I'm getting this content (Please, click on the image to enlarge it):
image

With all the supported map-options reported in the map-select

```
<map-select id="dim_corr" name="dim_corr">
<map-option>23</map-option>
<map-option>24</map-option>
<map-option>38</map-option>
<map-option>41</map-option>
... 
... 
... 
<map-option>241</map-option>
<map-option>242</map-option>
<map-option>243</map-option>
</map-select>
```

And the map-link containing the dim_corr parameter:

```<map-link tref="http://localhost:8080/geoserver/it.geosolutions/wms?request=GetFeatureInfo&amp;query_layers=rtadcp_custom&amp;crs=MapML:WGS84&amp;bbox={xmin},{ymin},{xmax},{ymax}&amp;language=en&amp;cql_filter=&amp;version=1.3.0&amp;dim_corr={dim_corr}&amp;transparent=true&amp;service=WMS&amp;layers=rtadcp_custom&amp;width={w}&amp;x={i}&amp;feature_count=50&amp;y={j}&amp;styles=point&amp;info_format=text/mapml&amp;height={h}" rel="query"/>```


When requesting the MapML output (with the check box on Use Tiles), I'm getting this (Please, click on the image to enlarge it):
image

Is it what you was expecting or are we still missing something?
Please, let us know.

**Comment by prushforth** [comment]
That's what I'm expecting.  I couldn't recall where I put that custom data, so I tried it with the states layer on population and couldn't reproduce the results, so probably user error.  Please proceed!

**Comment by dromagnoli** [comment]
Closing PR after having rebased to main (which introduced some commits from Joseph and Andrea).
Official PR is here:
https://github.com/geoserver/geoserver/pull/7806

**Pull request closed without merging**
